spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hew2022_11316?characterEncoding=utf8&serverTimezone=UTC
    username: hew2022_11316
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update